# Generated by Django 3.2.5 on 2022-08-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/img/yoga-1.jpg', upload_to='pages', verbose_name='Фото')),
                ('category_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.categoryphoto', verbose_name='Тема')),
            ],
        ),
    ]
